package GUI;

import Classes.Operations;
import Utilities.Utilities;
import Utilities.Validators;
import static Utilities.Utilities.numberOne;
import java.awt.event.KeyEvent;

/**
 *
 * @author Alberto Campos Hernandez ST1589
 */
public class CalcGui extends javax.swing.JFrame {

    /**
     * Creates new form CalcGui
     */
    public CalcGui() {
        initComponents();
        inputJtxt.setText("0"); // initialize the textbox with a zero

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputJtxt = new javax.swing.JLabel();
        inputJtxt = new javax.swing.JTextField();
        addJbtn = new javax.swing.JButton();
        oneJbtn = new javax.swing.JButton();
        twoJbtn = new javax.swing.JButton();
        threeJbtn = new javax.swing.JButton();
        subsJbtn = new javax.swing.JButton();
        fourJbtn = new javax.swing.JButton();
        fiveJbtn = new javax.swing.JButton();
        sixJbtn = new javax.swing.JButton();
        multJbtn = new javax.swing.JButton();
        sevenJbtn = new javax.swing.JButton();
        eightJbtn = new javax.swing.JButton();
        nineJbtn = new javax.swing.JButton();
        divJbtn = new javax.swing.JButton();
        zeroJbtn = new javax.swing.JButton();
        dotJbtn = new javax.swing.JButton();
        percJbtn = new javax.swing.JButton();
        clearJbtn = new javax.swing.JButton();
        negativeJbtn = new javax.swing.JButton();
        equalJbtn = new javax.swing.JButton();
        eraseJbtn = new javax.swing.JButton();
        cleanInputJbtn = new javax.swing.JButton();
        squareRootJbtn = new javax.swing.JButton();
        elevatedSquareJbtn = new javax.swing.JButton();
        elevatedNJbtn = new javax.swing.JButton();
        cosJbtn = new javax.swing.JButton();
        elevatedThreeJbtn = new javax.swing.JButton();
        tangJbtn = new javax.swing.JButton();
        factorialJbtn = new javax.swing.JButton();
        cubicRootJbtn = new javax.swing.JButton();
        senJbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculator V1.4_ST1589");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(490, 685));
        setResizable(false);
        getContentPane().setLayout(null);

        outputJtxt.setBackground(new java.awt.Color(204, 255, 204));
        outputJtxt.setFont(new java.awt.Font("Calculator", 1, 44)); // NOI18N
        outputJtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        outputJtxt.setOpaque(true);
        getContentPane().add(outputJtxt);
        outputJtxt.setBounds(60, 100, 360, 50);

        inputJtxt.setBackground(new java.awt.Color(204, 255, 204));
        inputJtxt.setFont(new java.awt.Font("Calculator", 0, 48)); // NOI18N
        inputJtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputJtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputJtxt.setOpaque(true);
        inputJtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputJtxtFocusGained(evt);
            }
        });
        inputJtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJtxtActionPerformed(evt);
            }
        });
        inputJtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputJtxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputJtxtKeyTyped(evt);
            }
        });
        getContentPane().add(inputJtxt);
        inputJtxt.setBounds(60, 150, 360, 50);

        addJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addJbtn.setText("+");
        addJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        addJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        addJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        addJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJbtnActionPerformed(evt);
            }
        });
        addJbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addJbtnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addJbtnKeyTyped(evt);
            }
        });
        getContentPane().add(addJbtn);
        addJbtn.setBounds(350, 470, 60, 50);

        oneJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        oneJbtn.setText("1");
        oneJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oneJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        oneJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        oneJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        oneJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(oneJbtn);
        oneJbtn.setBounds(140, 470, 60, 50);

        twoJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        twoJbtn.setText("2");
        twoJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twoJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        twoJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        twoJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        twoJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(twoJbtn);
        twoJbtn.setBounds(210, 470, 60, 50);

        threeJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        threeJbtn.setText("3");
        threeJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        threeJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        threeJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        threeJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        threeJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(threeJbtn);
        threeJbtn.setBounds(280, 470, 60, 50);

        subsJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        subsJbtn.setText("-");
        subsJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subsJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        subsJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        subsJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        subsJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(subsJbtn);
        subsJbtn.setBounds(350, 410, 60, 50);

        fourJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fourJbtn.setText("4");
        fourJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fourJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        fourJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        fourJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        fourJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(fourJbtn);
        fourJbtn.setBounds(140, 410, 60, 50);

        fiveJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fiveJbtn.setText("5");
        fiveJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fiveJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        fiveJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        fiveJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        fiveJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(fiveJbtn);
        fiveJbtn.setBounds(210, 410, 60, 50);

        sixJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        sixJbtn.setText("6");
        sixJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sixJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        sixJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        sixJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        sixJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(sixJbtn);
        sixJbtn.setBounds(280, 410, 60, 50);

        multJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        multJbtn.setText("x");
        multJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        multJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        multJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        multJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(multJbtn);
        multJbtn.setBounds(350, 350, 60, 50);

        sevenJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        sevenJbtn.setText("7");
        sevenJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sevenJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        sevenJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        sevenJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        sevenJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(sevenJbtn);
        sevenJbtn.setBounds(140, 350, 60, 50);

        eightJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        eightJbtn.setText("8");
        eightJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eightJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        eightJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        eightJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        eightJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eightJbtn);
        eightJbtn.setBounds(210, 350, 60, 50);

        nineJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nineJbtn.setText("9");
        nineJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nineJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        nineJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        nineJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        nineJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(nineJbtn);
        nineJbtn.setBounds(280, 350, 60, 50);

        divJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        divJbtn.setText("÷");
        divJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        divJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        divJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        divJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(divJbtn);
        divJbtn.setBounds(350, 290, 60, 50);

        zeroJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        zeroJbtn.setText("0");
        zeroJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zeroJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        zeroJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        zeroJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        zeroJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(zeroJbtn);
        zeroJbtn.setBounds(210, 530, 60, 50);

        dotJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dotJbtn.setText(".");
        dotJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dotJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        dotJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        dotJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        dotJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(dotJbtn);
        dotJbtn.setBounds(280, 530, 60, 50);

        percJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        percJbtn.setText("%");
        percJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        percJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        percJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        percJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        percJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(percJbtn);
        percJbtn.setBounds(350, 230, 60, 50);

        clearJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        clearJbtn.setText("C");
        clearJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearJbtn);
        clearJbtn.setBounds(210, 290, 60, 50);

        negativeJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        negativeJbtn.setText("(-)");
        negativeJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        negativeJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        negativeJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        negativeJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        negativeJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativeJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(negativeJbtn);
        negativeJbtn.setBounds(140, 530, 60, 50);

        equalJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        equalJbtn.setText("=");
        equalJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equalJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        equalJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        equalJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        equalJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(equalJbtn);
        equalJbtn.setBounds(350, 530, 60, 50);

        eraseJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        eraseJbtn.setText("E");
        eraseJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eraseJbtn.setMaximumSize(new java.awt.Dimension(41, 36));
        eraseJbtn.setMinimumSize(new java.awt.Dimension(41, 36));
        eraseJbtn.setPreferredSize(new java.awt.Dimension(41, 36));
        eraseJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eraseJbtn);
        eraseJbtn.setBounds(280, 290, 60, 50);

        cleanInputJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cleanInputJbtn.setText("CE");
        cleanInputJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanInputJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanInputJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cleanInputJbtn);
        cleanInputJbtn.setBounds(140, 290, 60, 50);

        squareRootJbtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        squareRootJbtn.setText("SQRT");
        squareRootJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        squareRootJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRootJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(squareRootJbtn);
        squareRootJbtn.setBounds(70, 530, 60, 50);

        elevatedSquareJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        elevatedSquareJbtn.setText("X²");
        elevatedSquareJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elevatedSquareJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevatedSquareJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(elevatedSquareJbtn);
        elevatedSquareJbtn.setBounds(70, 290, 60, 50);

        elevatedNJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        elevatedNJbtn.setText("X^n");
        elevatedNJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elevatedNJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevatedNJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(elevatedNJbtn);
        elevatedNJbtn.setBounds(70, 410, 60, 50);

        cosJbtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        cosJbtn.setText("COS");
        cosJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cosJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cosJbtn);
        cosJbtn.setBounds(140, 230, 60, 50);

        elevatedThreeJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        elevatedThreeJbtn.setText("X^3");
        elevatedThreeJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elevatedThreeJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevatedThreeJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(elevatedThreeJbtn);
        elevatedThreeJbtn.setBounds(70, 350, 60, 50);

        tangJbtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tangJbtn.setText("TAN");
        tangJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tangJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(tangJbtn);
        tangJbtn.setBounds(210, 230, 60, 50);

        factorialJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        factorialJbtn.setText("!");
        factorialJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        factorialJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(factorialJbtn);
        factorialJbtn.setBounds(280, 230, 60, 50);

        cubicRootJbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cubicRootJbtn.setText("3R ");
        cubicRootJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cubicRootJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubicRootJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cubicRootJbtn);
        cubicRootJbtn.setBounds(70, 470, 60, 50);

        senJbtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        senJbtn.setText("SIN");
        senJbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        senJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senJbtnActionPerformed(evt);
            }
        });
        getContentPane().add(senJbtn);
        senJbtn.setBounds(70, 230, 60, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/casiologo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 250, 60);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wallpaper_azul_oscuro_1920x1200_124.jpeg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, -110, 490, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String operator = "";
    public static Boolean stop;
    public static String input = "0", output = "";


    private void fourJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "4");
        Validators.firstNumberIsZero(input, "4");
        setInput(input);
        setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_fourJbtnActionPerformed

    private void nineJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "9");
        Validators.firstNumberIsZero(input, "9");
        setInput(input);
        setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_nineJbtnActionPerformed

    private void oneJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneJbtnActionPerformed

        if ("dev".equals(Operations.operator)) {
            inputJtxt.setText(inputJtxt.getText() + "1");
        } else {

            Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "1");
            Validators.firstNumberIsZero(input, "1");
            this.setInput(input);
            this.setOutput(output);
            inputJtxt.requestFocus();
        }
    }//GEN-LAST:event_oneJbtnActionPerformed

    private void twoJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "2");
        Validators.firstNumberIsZero(input, "2");
        this.setInput(input);
        this.setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_twoJbtnActionPerformed

    private void threeJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "3");
        Validators.firstNumberIsZero(input, "3");
        this.setInput(input);
        this.setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_threeJbtnActionPerformed

    private void fiveJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "5");
        Validators.firstNumberIsZero(input, "5");
        this.setInput(input);
        this.setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_fiveJbtnActionPerformed

    private void sixJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "6");
        Validators.firstNumberIsZero(input, "6");
        this.setInput(input);
        this.setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_sixJbtnActionPerformed

    private void sevenJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "7");
        Validators.firstNumberIsZero(input, "7");
        this.setInput(input);
        this.setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_sevenJbtnActionPerformed

    private void eightJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightJbtnActionPerformed
        Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "8");
        Validators.firstNumberIsZero(input, "8");
        this.setInput(input);
        this.setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_eightJbtnActionPerformed

    private void zeroJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroJbtnActionPerformed
        if ("dev".equals(Operations.operator)) {

            inputJtxt.setText(inputJtxt.getText() + "0");
        } else {
            if ("".equals(inputJtxt.getText())) {
                setInput(input);
            } else {
                if ("-".equals(inputJtxt.getText())) {
                    inputJtxt.setText(inputJtxt.getText());
                } else {
                    Validators.validateSyntaxError(inputJtxt.getText(), outputJtxt.getText(), "0");
                    Validators.firstNumberIsZero(input, "0");

                    this.setInput(input);
                    this.setOutput(output);
                    inputJtxt.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_zeroJbtnActionPerformed

    private void dotJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotJbtnActionPerformed
        Validators.validateSyntaxErrorDot(inputJtxt.getText(), outputJtxt.getText(), ".");
        this.setInput(input);
        this.setOutput(output);
        inputJtxt.requestFocus();
    }//GEN-LAST:event_dotJbtnActionPerformed

    private void percJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percJbtnActionPerformed
        operator = "%";
        if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1).endsWith("n"))) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 4) + operator);
        } else {
            if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("n"))) {
                outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                numberOne = Float.parseFloat(inputJtxt.getText());
                inputJtxt.setText("0");
            } else {
                if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("s"))) {
                    outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                    numberOne = Float.parseFloat(inputJtxt.getText());
                    inputJtxt.setText("0");
                } else {
                    if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().endsWith("!"))) {
                        outputJtxt.setText(inputJtxt.getText() + operator);
                        numberOne = Float.parseFloat(inputJtxt.getText());
                        inputJtxt.setText("0");
                    } else {
                        if (!"".equals(outputJtxt.getText())) {
                            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
                        }
                    }
                }
            }
        }

        Validators.validateOperator(inputJtxt.getText(), outputJtxt.getText(), operator);
        Validators.bigValidator(input, output);
        setInput(input);
        setOutput(output);
        Operations.operator = "%";
        inputJtxt.requestFocus();
    }//GEN-LAST:event_percJbtnActionPerformed

    private void clearJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJbtnActionPerformed
        Validators.inicialize();
        inputJtxt.setText("0");
        outputJtxt.setText("");
        Utilities.numberOne = 0;
        Utilities.numberTwo = 0;
        numberOne = 0;
        operator = "";
    }//GEN-LAST:event_clearJbtnActionPerformed

    private void negativeJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativeJbtnActionPerformed

        if (inputJtxt.getText().equals("")) {
            Validators.validateSyntaxErrorNegative(inputJtxt.getText(), outputJtxt.getText(), "-");
            this.setInput(input);
            this.setOutput(output);
            inputJtxt.requestFocus();
            inputJtxt.setText("0");
        } else {
            inputJtxt.setText(inputJtxt.getText());
        }
        if (inputJtxt.getText().equals("0")) {
            inputJtxt.setText("-");
        } else {
            if (inputJtxt.getText().charAt(0) == '-') {
                inputJtxt.setText(inputJtxt.getText().substring(1, inputJtxt.getText().length()));
            } else {
                if (inputJtxt.getText().charAt(0) == '0' && inputJtxt.getText().charAt(1) != '.') {
                    inputJtxt.setText(inputJtxt.getText().replace("0", ""));
                }
                inputJtxt.setText('-' + inputJtxt.getText());
            }
        }

    }//GEN-LAST:event_negativeJbtnActionPerformed

    private void equalJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalJbtnActionPerformed

        if (inputJtxt.getText().equals("Infinity")) {
            setInput(Validators.error);
            setOutput(Validators.error);
        } else {
            if (inputJtxt.getText().equals("-")) {
                inputJtxt.setText("-");
            } else {

                boolean validator = Validators.emptyInput(inputJtxt.getText());
                if (validator == true) {
                    this.setInput(Validators.error);
                    this.setOutput(Validators.error);
                } else {
                    boolean empty = Validators.emptyOutput(outputJtxt.getText());
                    if (inputJtxt.getText().equals(Validators.error)) {
                        input = "";
                        output = "";
                        this.setInput(input);
                        this.setOutput(output);
                    } else {
                        if (empty == true && "(^n)".equals(operator)) {
                            numberOne = Float.parseFloat(inputJtxt.getText());
                            Utilities.numberTwo = Utilities.numberTwo;
                            Operations.elevatedToN(numberOne, Utilities.numberTwo);
                            Validators.isEntire(Operations.C);
                            this.setInput(Validators.print());
                            output = "";
                        } else {
                            empty = Validators.emptyOutput(outputJtxt.getText());
                            if (empty == true && !"%".equals(operator)) {
                                Utilities.numberTwo = numberOne;
                                numberOne = Float.parseFloat(inputJtxt.getText());
                                this.setOutput("");
                            } else {
                                Utilities.numberTwo = (Float.parseFloat(inputJtxt.getText()));
                                Validators.isEntire(Utilities.numberTwo);
                                this.setOutput("");
                            }
                        }
                        switch (operator) {

                            case "+":

                                Operations.add(numberOne, Utilities.numberTwo);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);
                                } else {
                                    this.setInput(Validators.print());
                                    numberOne = Utilities.numberTwo;
                                    Utilities.numberTwo = Float.parseFloat(inputJtxt.getText());
                                }
                                break;

                            case "-":
                                Operations.subs(numberOne, Utilities.numberTwo);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);
                                } else {
                                    this.setInput(Validators.print());
                                    numberOne = Utilities.numberTwo;
                                    Utilities.numberTwo = Float.parseFloat(inputJtxt.getText());
                                }
                                break;
                            case "*":
                                Operations.mult(numberOne, Utilities.numberTwo);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);
                                } else {
                                    this.setInput(Validators.print());
                                    numberOne = Utilities.numberTwo;
                                    Utilities.numberTwo = Float.parseFloat(inputJtxt.getText());
                                }
                                break;
                            case "/":
                                if (Utilities.numberTwo == 0) {
                                    Validators.secondNumberIsZero(String.valueOf(Utilities.numberTwo));
                                    setInput(input);
                                    setOutput(output);
                                } else {

                                    Operations.div(numberOne, Utilities.numberTwo);
                                    Validators.isEntire(Operations.C);
                                    Validators.checkInfinity();
                                    if (input.equals(Validators.error)) {
                                        inputJtxt.setText(input);
                                        outputJtxt.setText(input);
                                    } else {
                                        this.setInput(Validators.print());
                                        numberOne = Utilities.numberTwo;
                                        Utilities.numberTwo = Float.parseFloat(inputJtxt.getText());
                                    }
                                }
                                break;
                            case "%":
                                Operations.perc(numberOne, Utilities.numberTwo);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "SQRT":
                                Operations.sqrt(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "CUBICRT":
                                Operations.cubicRoot(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "(^2)":
                                Operations.elevatedSquare(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "(^3)":
                                Operations.elevatedCube(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "(^n)":
                                Operations.elevatedToN(numberOne, Utilities.numberTwo);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                output = "";
                                break;
                            case "sin":
                                Operations.sin(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "cos":
                                Operations.cos(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "tan":
                                Operations.tan(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            case "!":
                                Operations.fact(numberOne);
                                Validators.isEntire(Operations.C);
                                Validators.checkInfinity();
                                if (input.equals(Validators.error)) {
                                    inputJtxt.setText(input);
                                    outputJtxt.setText(input);

                                } else {
                                    this.setInput(Validators.print());
                                }
                                break;
                            default:
                                Validators.checkInfinity();
                                this.setInput(input);
                        }
                    }
                }

            }
        }
        Validators.checkInfinity();
        inputJtxt.requestFocus();
    }//GEN-LAST:event_equalJbtnActionPerformed

    private void addJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJbtnActionPerformed

        operator = "+";

        if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1).endsWith("n"))) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 4) + operator);
        } else {
            if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("n"))) {
                outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                numberOne = Float.parseFloat(inputJtxt.getText());
                inputJtxt.setText("0");
            } else {
                if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("s"))) {
                    outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                    numberOne = Float.parseFloat(inputJtxt.getText());
                    inputJtxt.setText("0");
                } else {
                    if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().endsWith("!"))) {
                        outputJtxt.setText(inputJtxt.getText() + operator);
                        numberOne = Float.parseFloat(inputJtxt.getText());
                        inputJtxt.setText("0");
                    } else {
                        if (!"".equals(outputJtxt.getText())) {
                            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
                        }
                    }
                }
            }
        }

        Validators.validateOperator(inputJtxt.getText(), outputJtxt.getText(), operator);
        Validators.bigValidator(input, output);
        this.setInput(input);
        this.setOutput(output);
        Operations.operator = "+";
        inputJtxt.requestFocus();
    }//GEN-LAST:event_addJbtnActionPerformed

    private void subsJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsJbtnActionPerformed
        operator = "-";
        if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1).endsWith("n"))) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 4) + operator);
        } else {
            if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("n"))) {
                outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                numberOne = Float.parseFloat(inputJtxt.getText());
                inputJtxt.setText("0");
            } else {
                if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("s"))) {
                    outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                    numberOne = Float.parseFloat(inputJtxt.getText());
                    inputJtxt.setText("0");
                } else {
                    if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().endsWith("!"))) {
                        outputJtxt.setText(inputJtxt.getText() + operator);
                        numberOne = Float.parseFloat(inputJtxt.getText());
                        inputJtxt.setText("0");
                    } else {
                        if (!"".equals(outputJtxt.getText())) {
                            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
                        }
                    }
                }
            }
        }

        Validators.validateOperator(inputJtxt.getText(), outputJtxt.getText(), operator);
        Validators.bigValidator(input, output);
        this.setInput(input);
        this.setOutput(output);
        Operations.operator = "-";
        inputJtxt.requestFocus();
    }//GEN-LAST:event_subsJbtnActionPerformed

    private void multJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multJbtnActionPerformed
        operator = "*";
        if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1).endsWith("n"))) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 4) + operator);
        } else {
            if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("n"))) {
                outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                numberOne = Float.parseFloat(inputJtxt.getText());
                inputJtxt.setText("0");
            } else {
                if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("s"))) {
                    outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                    numberOne = Float.parseFloat(inputJtxt.getText());
                    inputJtxt.setText("0");
                } else {
                    if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().endsWith("!"))) {
                        outputJtxt.setText(inputJtxt.getText() + operator);
                        numberOne = Float.parseFloat(inputJtxt.getText());
                        inputJtxt.setText("0");
                    } else {
                        if (!"".equals(outputJtxt.getText())) {
                            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
                        }
                    }
                }
            }
        }

        Validators.validateOperator(inputJtxt.getText(), outputJtxt.getText(), operator);
        Validators.bigValidator(input, output);
        this.setInput(input);
        this.setOutput(output);
        Operations.operator = "*";
        inputJtxt.requestFocus();
    }//GEN-LAST:event_multJbtnActionPerformed

    private void divJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divJbtnActionPerformed

        operator = "/";
        if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1).endsWith("n"))) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 4) + operator);
        } else {
            if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("n"))) {
                outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                numberOne = Float.parseFloat(inputJtxt.getText());
                inputJtxt.setText("0");
            } else {
                if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().substring(0, outputJtxt.getText().length()).endsWith("s"))) {
                    outputJtxt.setText(inputJtxt.getText().substring(0, inputJtxt.getText().length()) + operator);
                    numberOne = Float.parseFloat(inputJtxt.getText());
                    inputJtxt.setText("0");
                } else {
                    if ((!"".equals(outputJtxt.getText()) && outputJtxt.getText().endsWith("!"))) {
                        outputJtxt.setText(inputJtxt.getText() + operator);
                        numberOne = Float.parseFloat(inputJtxt.getText());
                        inputJtxt.setText("0");
                    } else {
                        if (!"".equals(outputJtxt.getText())) {
                            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
                        }
                    }
                }
            }
        }

        Validators.validateOperator(inputJtxt.getText(), outputJtxt.getText(), operator);
        Validators.bigValidator(input, output);
        this.setInput(input);
        this.setOutput(output);
        Operations.operator = "/";
        inputJtxt.requestFocus();

    }//GEN-LAST:event_divJbtnActionPerformed
    /*This listen the keyboard and activates the button that match with the order*/
    private void inputJtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputJtxtKeyTyped
        Validators.keyTyped(evt);
        char keyPressed = evt.getKeyChar();
        if ("dev".equals(Operations.operator)) {
            evt.consume();
        } else {
            switch (keyPressed) {

                case '0':
                    zeroJbtn.doClick();
                    break;
                case '1':
                    oneJbtn.doClick();
                    break;
                case '2':
                    twoJbtn.doClick();
                    break;
                case '3':
                    threeJbtn.doClick();
                    break;
                case '4':
                    fourJbtn.doClick();
                    break;
                case '5':
                    fiveJbtn.doClick();
                    break;
                case '6':
                    sixJbtn.doClick();
                    break;

                case '7':
                    sevenJbtn.doClick();
                    break;
                case '8':
                    eightJbtn.doClick();
                    break;
                case '9':
                    nineJbtn.doClick();
                    break;
                case '+':
                    addJbtn.doClick();
                    break;
                case '-':
                    subsJbtn.doClick();
                    break;
                case '*':
                    multJbtn.doClick();
                    break;
                case '/':
                    divJbtn.doClick();
                    break;
                case '%':
                    percJbtn.doClick();
                    break;
                case '=':
                    equalJbtn.doClick();
                    break;
                case '.':
                    dotJbtn.doClick();
                    break;
                case '_':
                    negativeJbtn.doClick();
                    break;
                case KeyEvent.VK_ENTER:
                    equalJbtn.doClick();
                    break;
                case KeyEvent.VK_DELETE:
                    clearJbtn.doClick();
                    break;
//            case KeyEvent.VK_BACK_SPACE:
//                eraseJbtn.doClick();
//                break;
                default:

            }
        }

    }//GEN-LAST:event_inputJtxtKeyTyped


    private void addJbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addJbtnKeyPressed

    }//GEN-LAST:event_addJbtnKeyPressed

    private void addJbtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addJbtnKeyTyped

    }//GEN-LAST:event_addJbtnKeyTyped

    private void eraseJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseJbtnActionPerformed

        Validators.emptyInput(inputJtxt.getText());
        if (Validators.emptyInput == true) {
            this.setInput("0");

        } else {
            if (!"0".equals(inputJtxt.getText())) {
                this.setInput(inputJtxt.getText().substring(0, inputJtxt.getText().length() - 1));

                if ("".equals(inputJtxt.getText())) {
                    this.setInput("0");
                }
            } else {
                this.setInput("0");
            }
        }
        inputJtxt.requestFocus();
    }//GEN-LAST:event_eraseJbtnActionPerformed

    private void inputJtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJtxtActionPerformed

    }//GEN-LAST:event_inputJtxtActionPerformed
    /*This method does not allow the user to use the CTRL and the ALT keys
    in order to do not set letter or other symbols on the textbox*/
    private void inputJtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputJtxtKeyPressed
        if (evt.isAltDown() || evt.isControlDown()) {
            evt.consume();
        }

    }//GEN-LAST:event_inputJtxtKeyPressed

    private void inputJtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputJtxtFocusGained

    }//GEN-LAST:event_inputJtxtFocusGained

    private void cleanInputJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanInputJbtnActionPerformed
        if ("dev".equals(Operations.operator)) {
            outputJtxt.setText("");
            inputJtxt.setText("");
            input = "";
            inputJtxt.requestFocus();
        } else {

            inputJtxt.setText("0");
            input = "0";
            inputJtxt.requestFocus();
    }//GEN-LAST:event_cleanInputJbtnActionPerformed
    }
    private void squareRootJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRootJbtnActionPerformed
        operator = "SQRT";
        if (!"".equals(outputJtxt.getText())) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
        }
        Validators.validateOperator(inputJtxt.getText(), output, operator);
        Validators.bigValidator(input, "");
        this.setInput("0");
        this.setOutput(output);
        Operations.operator = "SQRT";
        Operations.sqrt(numberOne);
        Validators.isEntire(Operations.C);
        Validators.checkInfinity();
        this.setInput(Validators.print());
        inputJtxt.requestFocus();
    }//GEN-LAST:event_squareRootJbtnActionPerformed

    private void cubicRootJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubicRootJbtnActionPerformed
        operator = "CUBICRT";
        if (!"".equals(outputJtxt.getText())) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
        }
        Validators.validateOperator(inputJtxt.getText(), output, operator);
        Validators.bigValidator(input, "");
        this.setInput("0");
        this.setOutput(output);
        Operations.operator = "CUBICRT";
        Operations.cubicRoot(numberOne);
        Validators.isEntire(Operations.C);
        Validators.checkInfinity();
        this.setInput(Validators.print());
        inputJtxt.requestFocus();
    }//GEN-LAST:event_cubicRootJbtnActionPerformed

    private void elevatedSquareJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevatedSquareJbtnActionPerformed

        operator = "(^2)";
        if (!"".equals(outputJtxt.getText())) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
        }
        Validators.validateOperator(inputJtxt.getText(), output, operator);
        Validators.bigValidator(input, "");
        this.setInput("0");
        this.setOutput(output);
        Operations.operator = "(^2)";
        Operations.elevatedSquare(numberOne);
        Validators.isEntire(Operations.C);
        Validators.checkInfinity();
        this.setInput(Validators.print());
        inputJtxt.requestFocus();

    }//GEN-LAST:event_elevatedSquareJbtnActionPerformed

    private void elevatedThreeJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevatedThreeJbtnActionPerformed
        operator = "(^3)";
        if (!"".equals(outputJtxt.getText())) {
            outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
        }
        Validators.validateOperator(inputJtxt.getText(), output, operator);
        Validators.bigValidator(input, "");
        this.setInput("0");
        this.setOutput(output);
        Operations.operator = "(^3)";
        Operations.elevatedCube(numberOne);
        Validators.isEntire(Operations.C);
        this.setInput(Validators.print());
        inputJtxt.requestFocus();
    }//GEN-LAST:event_elevatedThreeJbtnActionPerformed

    private void elevatedNJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevatedNJbtnActionPerformed
        operator = "(^n)";
        try {
            if (!"".equals(outputJtxt.getText())) {

                outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 4) + operator);
            }
            Validators.validateOperator(inputJtxt.getText(), outputJtxt.getText(), operator);
            Validators.bigValidator(input, output);
            this.setInput("0");
            this.setOutput(output);
            Operations.operator = "(^n)";
            Operations.elevatedToN(numberOne, Utilities.numberTwo);
            Validators.isEntire(Operations.C);
            Validators.checkInfinity();
            this.setInput("0");
            inputJtxt.requestFocus();

        } catch (StringIndexOutOfBoundsException outOf) {
            setInput(Validators.error);
            setOutput(Validators.error);
        }
    }//GEN-LAST:event_elevatedNJbtnActionPerformed

    private void senJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senJbtnActionPerformed
        operator = "sin";
        try {
            if (!"".equals(outputJtxt.getText())) {
                outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 3) + operator);
            }
            Validators.validateOperator(inputJtxt.getText(), output, operator);
            Validators.bigValidator(input, "");
            this.setInput("0");
            this.setOutput(output);
            Operations.operator = "(sin)";
            Operations.sin(numberOne);
            Validators.checkInfinity();
            if (input.equals(Validators.error)) {
                setInput(input);
                setOutput(input);
            } else {
                Validators.isEntire(Operations.C);
                this.setInput(Validators.print());
                inputJtxt.requestFocus();
            }
        } catch (StringIndexOutOfBoundsException outOf) {
            setInput(Validators.error);
            setOutput(Validators.error);
        }
    }//GEN-LAST:event_senJbtnActionPerformed

    private void cosJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosJbtnActionPerformed
        operator = "cos";
        try {
            if (!"".equals(outputJtxt.getText())) {
                outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 3) + operator);
            }
            Validators.validateOperator(inputJtxt.getText(), output, operator);
            Validators.bigValidator(input, "");
            this.setInput("0");
            this.setOutput(output);
            Operations.operator = "(cos)";
            Operations.cos(numberOne);
            Validators.isEntire(Operations.C);
            Validators.checkInfinity();
            this.setInput(Validators.print());
            inputJtxt.requestFocus();

        } catch (StringIndexOutOfBoundsException outOf) {
            setInput(Validators.error);
            setOutput(Validators.error);
        }
    }//GEN-LAST:event_cosJbtnActionPerformed

    private void tangJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangJbtnActionPerformed
        operator = "tan";
        try {
            if (!"".equals(outputJtxt.getText())) {
                outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 3) + operator);
            }
            Validators.validateOperator(inputJtxt.getText(), output, operator);
            Validators.bigValidator(input, "");
            this.setInput("0");
            this.setOutput(output);
            Operations.operator = "(cos)";
            Operations.tan(numberOne);
            Validators.isEntire(Operations.C);
            Validators.checkInfinity();
            this.setInput(Validators.print());
            inputJtxt.requestFocus();
        } catch (StringIndexOutOfBoundsException outOf) {
            setInput(Validators.error);
            setOutput(Validators.error);
        }
    }//GEN-LAST:event_tangJbtnActionPerformed

    private void factorialJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialJbtnActionPerformed
        operator = "!";
        try {
            if (!"".equals(outputJtxt.getText())) {
                outputJtxt.setText(outputJtxt.getText().substring(0, outputJtxt.getText().length() - 1) + operator);
            }
            Validators.validateOperator(inputJtxt.getText(), output, operator);
            Validators.bigValidator(input, "");
            this.setInput("0");
            this.setOutput(output);
            Operations.operator = "(!)";
            Operations.fact(numberOne);
            Validators.checkInfinity();
            if (input.equals(Validators.error) || Operations.C == 0) {
                inputJtxt.setText(input);
                outputJtxt.setText(input);
            } else {
                Validators.isEntire(Operations.C);
                this.setInput(Validators.print());
                inputJtxt.requestFocus();
            }
        } catch (StringIndexOutOfBoundsException outOf) {
            setInput(Validators.error);
            setOutput(Validators.error);
        }
    }//GEN-LAST:event_factorialJbtnActionPerformed

    /*This method prints to the textbox*/   //to be inplemented yet
    public void setInput(String input) {
        inputJtxt.setText(input);
    }

    /*This method prints to the label*/   //to be inplemented yet
    private void setOutput(String output) {
        outputJtxt.setText(output);
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJbtn;
    private javax.swing.JButton cleanInputJbtn;
    private javax.swing.JButton clearJbtn;
    private javax.swing.JButton cosJbtn;
    private javax.swing.JButton cubicRootJbtn;
    private javax.swing.JButton divJbtn;
    private javax.swing.JButton dotJbtn;
    private javax.swing.JButton eightJbtn;
    private javax.swing.JButton elevatedNJbtn;
    private javax.swing.JButton elevatedSquareJbtn;
    private javax.swing.JButton elevatedThreeJbtn;
    private javax.swing.JButton equalJbtn;
    private javax.swing.JButton eraseJbtn;
    private javax.swing.JButton factorialJbtn;
    private javax.swing.JButton fiveJbtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton fourJbtn;
    private javax.swing.JTextField inputJtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multJbtn;
    private javax.swing.JButton negativeJbtn;
    private javax.swing.JButton nineJbtn;
    private javax.swing.JButton oneJbtn;
    private javax.swing.JLabel outputJtxt;
    private javax.swing.JButton percJbtn;
    private javax.swing.JButton senJbtn;
    private javax.swing.JButton sevenJbtn;
    private javax.swing.JButton sixJbtn;
    private javax.swing.JButton squareRootJbtn;
    private javax.swing.JButton subsJbtn;
    private javax.swing.JButton tangJbtn;
    private javax.swing.JButton threeJbtn;
    private javax.swing.JButton twoJbtn;
    private javax.swing.JButton zeroJbtn;
    // End of variables declaration//GEN-END:variables
}
